version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/futsal_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  db:
    container_name: futsal-postgres
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root  # Sets the password for the default user 'postgres'
      POSTGRES_DB: futsal_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data

volumes:
  postgres_data:
    driver: local  # Use a local volume for persistence

