apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "futsal.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "futsal.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
