apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: futsal-backend-app
  labels:
    {{- include "futsal.backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: futsal-backend-app
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef: { key: /futsal/sandbox/jwt, property: secret }
    - secretKey: MAIL_HOST
      remoteRef: { key: /futsal/sandbox/smtp, property: host }
    - secretKey: MAIL_PORT
      remoteRef: { key: /futsal/sandbox/smtp, property: port }
    - secretKey: MAIL_USERNAME
      remoteRef: { key: /futsal/sandbox/smtp, property: username }
    - secretKey: MAIL_PASSWORD
      remoteRef: { key: /futsal/sandbox/smtp, property: password }
