{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  labels:
    {{- include "futsal.backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "futsal.backend.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
{{- end }}
