apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: futsal-uploads
  labels:
    {{- include "futsal.backend.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.uploads.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.uploads.size | quote }}
